//Should add the the character image to the character object
const characterImages = {
    "Luke Skywalker": "Luke-Skywalker3.jpeg",
    "C-3PO": "C-3PO_2.jpg",
    "R2-D2": "R2-D2_2.jpg",
    "Darth Vader": "Darth-Vader2.jpg",
    "Leia Organa": "Leia-Organa3.jpg",
    "Owen Lars": "owen-lars.jpg",
    "Beru Whitesun lars": "Beru-Whitesun-lars3.jpeg",
    "R5-D4": "R5-D4.jpg",
    "Biggs Darklighter": "Biggs-Darklighter2.jpg",
    "Obi-Wan Kenobi": "Obi-Wan-Kenobi2.jpg",
    "Anakin Skywalker": "Anakin-Skywalker1.jpg",
    "Wilhuff Tarkin": "Wilhuff-Tarkin1.jpg",
    "Chewbacca": "Chewbacca2.jpg",
    "Han Solo": "Han-Solo1.jpeg",
    "Greedo": "Greedo1.jpg",
    "Jabba Desilijic Tiure": "Jabba-Desilijic-Tiure.jpeg",
    "Wedge Antilles": "Wedge-Antilles.jpeg",
    "Jek Tono Porkins": "Jek-Tono-Porkins.jpeg",
    "Yoda": "Yoda1.jpg",
    "Palpatine": "Palpatine1.jpeg",
    "Boba Fett": "Boba-Fett1.jpeg",
    "IG-88": "ig-88_2.jpeg",
    "Bossk": "Bossk3.jpg",
    "Lando Calrissian": "Lando-Calrissian1.jpeg",
    "Lobot": "Lobot1.jpg",
    "Ackbar": "Ackbar1.jpeg",
    "Mon Mothma": "Mon-Mothma2.jpeg",
    "Arvel Crynyd": "Arvel-Crynyd1.jpeg",
    "Wicket Systri Warrick": "Wicket-Systri-Warrick1.jpeg",
    "Nien Nunb": "Nien-Nunb1.jpeg",
    "Qui-Gon Jinn": "Qui-Gon_Jinn1.jpeg",
    "Nute Gunray": "Nute-Gunray2.jpg",
    "Finis Valorum": "Finis-Valorum1.jpeg",
    "Padmé Amidala": "Padmé-Amidala1.jpeg",
    "Jar Jar Binks": "Jar-Jar-Binks1.jpeg",
    "Roos Tarpals": "Roos-Tarpals1.jpeg",
    "Rugor Nass": "Rugor-Nass1.jpg",
    "Ric Olié": "Ric-Olié1.jpg",
    "Watto": "Watto1.jpeg",
    "Sebulba": "",
    "Quarsh Panaka": "",
    "Shmi Skywalker": "",
    "Darth Maul": "",
    "Bib Fortuna": "",
    "Ayla Secura": "",
    "Ratts Tyerel": "",
    "Dud Bolt": "",
    "Gasgano": "",
    "Ben Quadinaros": "",
    "Mace Windu": "",
    "Ki-Adi-Mundi": "",
    "Kit Fisto": "",
    "Eeth Koth": "",
    "Adi Gallia": "",
    "Saesee Tiin": "",
    "Yarael Poof": "",
    "Plo Koon": "",
    "Mas Amedda": "",
    "Gregar Typho": "",
    "Cordé": "",
    "Cliegg Lars": "",
    "Poggle the Lesser": "",
    "Luminara Unduli": "",
    "Barriss Offee": "",
    "Dormé": "",
    "Dooku": "",
    "Bail Prestor Organa": "",
    "Jango Fett": "",
    "Zam Wesell": "",
    "Dexter Jettster": "",
    "Lama Su": "",
    "Taun We": "",
    "Jocasta Nu": "",
    "R4-P17": "",
    "Wat Tambor": "",
    "San Hill": "",
    "Shaak Ti": "",
    "Grievous": "",
    "Tarfful": "",
    "Raymus Antilles": "",
    "Sly Moore": "",
    "Tion Medon": ""
};